name: Deploy on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create image
        run: docker build . -t ghcr.io/nexiosit/devops/enrik:${{ github.sha }}

      - name: testing something
        run: echo ghcr.io/nexiosit/devops/enrik:${{ github.sha }}

      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push docker container
        run: |
          docker push ghcr.io/nexiosit/devops/enrik:${{ github.sha }}
